import { DataTable } from "@/components/DataTable";
import { CustomerUsed } from "@/types/CustomerUsed";
import { CustomerTableColumns } from "./CustomerTableColumn";

const customers: CustomerUsed[] = [
  {
    id: 1,
    name: "Nguyễn Văn An",
    address: "Quận 1, TP. Hồ Chí Minh",
    serviceName: "Giặt thảm văn phòng",
    beforeImage: "./assets/images/before_clean_product.png",
    afterImage: "./assets/images/after_clean_product.png",
    url: "https://example.com/services/giat-tham-van-phong",
  },
  {
    id: 2,
    name: "Trần Thị Bích Ngọc",
    address: "Quận 3, TP. Hồ Chí Minh",
    serviceName: "Giặt sofa gia đình",
    beforeImage: "./assets/images/before_clean_product.png",
    afterImage: "./assets/images/after_clean_product.png",
    url: "https://example.com/services/giat-sofa-gia-dinh",
  },
  {
    id: 3,
    name: "Lê Quang Minh",
    address: "Quận 7, TP. Hồ Chí Minh",
    serviceName: "Giặt rèm cửa",
    beforeImage: "./assets/images/before_clean_product.png",
    afterImage: "./assets/images/after_clean_product.png",
    url: "https://example.com/services/giat-rem-cua",
  },
  {
    id: 4,
    name: "Phạm Thị Thanh",
    address: "Quận Bình Thạnh, TP. Hồ Chí Minh",
    serviceName: "Giặt ghế ô tô",
    beforeImage: "./assets/images/before_clean_product.png",
    afterImage: "./assets/images/after_clean_product.png",
    url: "https://example.com/services/giat-ghe-o-to",
  },
  {
    id: 5,
    name: "Hoàng Văn Hải",
    address: "Quận Tân Bình, TP. Hồ Chí Minh",
    serviceName: "Vệ sinh nệm",
    beforeImage: "./assets/images/before_clean_product.png",
    afterImage: "./assets/images/after_clean_product.png",
    url: "https://example.com/services/ve-sinh-nem",
  },
  {
    id: 6,
    name: "Nguyễn Thị Mai",
    address: "Quận Phú Nhuận, TP. Hồ Chí Minh",
    serviceName: "Giặt ghế văn phòng",
    beforeImage: "./assets/images/before_clean_product.png",
    afterImage: "./assets/images/after_clean_product.png",
    url: "https://example.com/services/giat-ghe-van-phong",
  },
  {
    id: 7,
    name: "Lê Minh Tâm",
    address: "Quận 10, TP. Hồ Chí Minh",
    serviceName: "Giặt rèm cửa gia đình",
    beforeImage: "./assets/images/before_clean_product.png",
    afterImage: "./assets/images/after_clean_product.png",
    url: "https://example.com/services/giat-rem-cua-gia-dinh",
  },
  {
    id: 8,
    name: "Trần Anh Dũng",
    address: "Quận 5, TP. Hồ Chí Minh",
    serviceName: "Vệ sinh ghế da ô tô",
    beforeImage: "./assets/images/before_clean_product.png",
    afterImage: "./assets/images/after_clean_product.png",
    url: "https://example.com/services/ve-sinh-ghe-da-o-to",
  },
  {
    id: 9,
    name: "Phạm Thị Lan",
    address: "Quận Thủ Đức, TP. Hồ Chí Minh",
    serviceName: "Giặt thảm gia đình",
    beforeImage: "./assets/images/before_clean_product.png",
    afterImage: "./assets/images/after_clean_product.png",
    url: "https://example.com/services/giat-tham-gia-dinh",
  },
  {
    id: 10,
    name: "Nguyễn Văn Bình",
    address: "Quận Gò Vấp, TP. Hồ Chí Minh",
    serviceName: "Giặt sofa cao cấp",
    beforeImage: "./assets/images/before_clean_product.png",
    afterImage: "./assets/images/after_clean_product.png",
    url: "https://example.com/services/giat-sofa-cao-cap",
  },
  {
    id: 11,
    name: "Đỗ Thị Cẩm Tiên",
    address: "Quận 4, TP. Hồ Chí Minh",
    serviceName: "Vệ sinh nệm khách sạn",
    beforeImage: "./assets/images/before_clean_product.png",
    afterImage: "./assets/images/after_clean_product.png",
    url: "https://example.com/services/ve-sinh-nem-khach-san",
  },
  {
    id: 12,
    name: "Vũ Hoàng Anh",
    address: "Quận 2, TP. Hồ Chí Minh",
    serviceName: "Vệ sinh nội thất ô tô",
    beforeImage: "./assets/images/before_clean_product.png",
    afterImage: "./assets/images/after_clean_product.png",
    url: "https://example.com/services/ve-sinh-noi-that-o-to",
  },
  {
    id: 13,
    name: "Lý Thanh Sơn",
    address: "Quận 6, TP. Hồ Chí Minh",
    serviceName: "Giặt ghế quán cà phê",
    beforeImage: "./assets/images/before_clean_product.png",
    afterImage: "./assets/images/after_clean_product.png",
    url: "https://example.com/services/giat-ghe-quan-ca-phe",
  },
  {
    id: 14,
    name: "Phan Thị Ngọc Bích",
    address: "Quận Bình Tân, TP. Hồ Chí Minh",
    serviceName: "Giặt rèm cửa văn phòng",
    beforeImage: "./assets/images/before_clean_product.png",
    afterImage: "./assets/images/after_clean_product.png",
    url: "https://example.com/services/giat-rem-cua-van-phong",
  },
  {
    id: 15,
    name: "Nguyễn Văn Hưng",
    address: "Huyện Nhà Bè, TP. Hồ Chí Minh",
    serviceName: "Vệ sinh ghế sofa khách sạn",
    beforeImage: "./assets/images/before_clean_product.png",
    afterImage: "./assets/images/after_clean_product.png",
    url: "https://example.com/services/ve-sinh-ghe-sofa-khach-san",
  },
  {
    id: 16,
    name: "Lê Phương Trinh",
    address: "Quận 12, TP. Hồ Chí Minh",
    serviceName: "Giặt thảm xe hơi",
    beforeImage: "./assets/images/before_clean_product.png",
    afterImage: "./assets/images/after_clean_product.png",
    url: "https://example.com/services/giat-tham-xe-hoi",
  },
  {
    id: 17,
    name: "Trần Văn Thành",
    address: "Huyện Hóc Môn, TP. Hồ Chí Minh",
    serviceName: "Vệ sinh đệm cao cấp",
    beforeImage: "./assets/images/before_clean_product.png",
    afterImage: "./assets/images/after_clean_product.png",
    url: "https://example.com/services/ve-sinh-dem-cao-cap",
  },
  {
    id: 18,
    name: "Phạm Thị Minh Tuyết",
    address: "Quận 8, TP. Hồ Chí Minh",
    serviceName: "Giặt rèm cửa biệt thự",
    beforeImage: "./assets/images/before_clean_product.png",
    afterImage: "./assets/images/after_clean_product.png",
    url: "https://example.com/services/giat-rem-cua-biet-thu",
  },
  {
    id: 19,
    name: "Nguyễn Thị Kim Chi",
    address: "Quận 11, TP. Hồ Chí Minh",
    serviceName: "Vệ sinh nội thất văn phòng",
    beforeImage: "./assets/images/before_clean_product.png",
    afterImage: "./assets/images/after_clean_product.png",
    url: "https://example.com/services/ve-sinh-noi-that-van-phong",
  },
  {
    id: 20,
    name: "Bùi Văn Đức",
    address: "Huyện Bình Chánh, TP. Hồ Chí Minh",
    serviceName: "Giặt ghế tiệc cưới",
    beforeImage: "./assets/images/before_clean_product.png",
    afterImage: "./assets/images/after_clean_product.png",
    url: "https://example.com/services/giat-ghe-tiec-cuoi",
  },
];

export default function CustomerList() {
  return (
    <section className="container mx-auto mt-[60px]">
      <h2 className="text-2xl font-bold mb-4">
        Danh sách khách hàng sử dụng dịch vụ
      </h2>
      <DataTable columns={CustomerTableColumns} data={customers} />
    </section>
  );
}
